/******************************************************************************/
/****        Generated by IBExpert 2023.4.14.1 12/07/2023 16:17:11         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE '127.0.0.1/3050:cadcli'
USER 'SYSDBA' PASSWORD 'pfglessa'
PAGE_SIZE 8192
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE CLIENTE (
    ID           VARCHAR(14) DEFAULT '' NOT NULL,
    NOME         VARCHAR(100),
    ENDERECO     VARCHAR(100),
    NUMERO       INTEGER DEFAULT 0,
    CEP          VARCHAR(8),
    IDMUNICIPIO  INTEGER DEFAULT 0,
    NASCIMENTO   DATE
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTEPK PRIMARY KEY (ID);
